-- Billing V1 foundation. This migration is applied only through the protected
-- post-B02 operator path; it is intentionally not part of generic Up.

CREATE TABLE IF NOT EXISTS electricity_rate_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(64) NOT NULL,
    version_code VARCHAR(128) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    source_organization VARCHAR(200) NOT NULL,
    source_document VARCHAR(200) NOT NULL,
    source_url VARCHAR(500),
    approval_reference VARCHAR(200) NOT NULL,
    source_checksum CHAR(64),
    currency CHAR(3) NOT NULL,
    includes_tax BOOLEAN NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT electricity_rate_sets_version_key UNIQUE (provider, version_code),
    CONSTRAINT electricity_rate_sets_date_check CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT electricity_rate_sets_status_check CHECK (status IN ('DRAFT', 'AUTHORITATIVE', 'RETIRED')),
    CONSTRAINT electricity_rate_sets_checksum_check CHECK (source_checksum IS NULL OR source_checksum ~ '^[0-9a-fA-F]{64}$')
);

ALTER TABLE electricity_rate_sets
    DROP CONSTRAINT IF EXISTS electricity_rate_sets_authoritative_no_overlap;
ALTER TABLE electricity_rate_sets
    ADD CONSTRAINT electricity_rate_sets_authoritative_no_overlap
    EXCLUDE USING gist (
        provider WITH =,
        daterange(effective_from, COALESCE(effective_to, 'infinity'::date), '[)') WITH &&
    ) WHERE (status IN ('AUTHORITATIVE', 'RETIRED'));

CREATE INDEX IF NOT EXISTS idx_electricity_rate_sets_effective
    ON electricity_rate_sets (provider, effective_from, effective_to);

CREATE TABLE IF NOT EXISTS electricity_tariff_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code VARCHAR(100) NOT NULL UNIQUE,
    electricity_tariff VARCHAR(32) NOT NULL,
    billing_method VARCHAR(32) NOT NULL,
    usage_class VARCHAR(64),
    calculator_kind VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT electricity_tariff_plans_tariff_check CHECK (electricity_tariff IN ('LIGHTING_COMMERCIAL', 'LIGHTING_NONCOMMERCIAL')),
    CONSTRAINT electricity_tariff_plans_method_check CHECK (billing_method = 'NON_TOU'),
    CONSTRAINT electricity_tariff_plans_calculator_check CHECK (calculator_kind = 'PROGRESSIVE_NON_TOU'),
    CONSTRAINT electricity_tariff_plans_usage_check CHECK (
        (electricity_tariff = 'LIGHTING_COMMERCIAL' AND usage_class IS NULL)
        OR (electricity_tariff = 'LIGHTING_NONCOMMERCIAL' AND usage_class IN ('RESIDENTIAL', 'NON_RESIDENTIAL_NONCOMMERCIAL'))
    )
);

CREATE TABLE IF NOT EXISTS electricity_rate_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_set_id BIGINT NOT NULL REFERENCES electricity_rate_sets(id) ON DELETE RESTRICT,
    tariff_plan_id BIGINT NOT NULL REFERENCES electricity_tariff_plans(id) ON DELETE RESTRICT,
    minimum_monthly_charge NUMERIC(20,6) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT electricity_rate_plans_set_plan_key UNIQUE (rate_set_id, tariff_plan_id),
    CONSTRAINT electricity_rate_plans_minimum_check CHECK (minimum_monthly_charge >= 0)
);

CREATE TABLE IF NOT EXISTS electricity_rate_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_plan_id BIGINT NOT NULL REFERENCES electricity_rate_plans(id) ON DELETE RESTRICT,
    season VARCHAR(20) NOT NULL,
    tier_order INTEGER NOT NULL,
    lower_kwh NUMERIC(20,6) NOT NULL,
    upper_kwh NUMERIC(20,6),
    rate_per_kwh NUMERIC(20,6) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT electricity_rate_tiers_key UNIQUE (rate_plan_id, season, tier_order),
    CONSTRAINT electricity_rate_tiers_season_check CHECK (season IN ('SUMMER', 'NON_SUMMER')),
    CONSTRAINT electricity_rate_tiers_order_check CHECK (tier_order > 0),
    CONSTRAINT electricity_rate_tiers_bounds_check CHECK (lower_kwh >= 0 AND (upper_kwh IS NULL OR upper_kwh > lower_kwh)),
    CONSTRAINT electricity_rate_tiers_rate_check CHECK (rate_per_kwh >= 0)
);

CREATE INDEX IF NOT EXISTS idx_electricity_rate_tiers_lookup
    ON electricity_rate_tiers (rate_plan_id, season, tier_order);

CREATE TABLE IF NOT EXISTS shop_billing_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id BIGINT NOT NULL REFERENCES shops(id) ON DELETE RESTRICT,
    tariff_plan_id BIGINT NOT NULL REFERENCES electricity_tariff_plans(id) ON DELETE RESTRICT,
    valid_from DATE NOT NULL,
    valid_to DATE,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT shop_billing_assignments_date_check CHECK (valid_to IS NULL OR valid_to > valid_from)
);

ALTER TABLE shop_billing_assignments
    DROP CONSTRAINT IF EXISTS shop_billing_assignments_no_overlap;
ALTER TABLE shop_billing_assignments
    ADD CONSTRAINT shop_billing_assignments_no_overlap
    EXCLUDE USING gist (
        shop_id WITH =,
        daterange(valid_from, COALESCE(valid_to, 'infinity'::date), '[)') WITH &&
    );

CREATE INDEX IF NOT EXISTS idx_shop_billing_assignments_lookup
    ON shop_billing_assignments (shop_id, valid_from DESC);

CREATE OR REPLACE FUNCTION billing_rate_set_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.status IN ('AUTHORITATIVE', 'RETIRED') THEN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'authoritative electricity rate sets are immutable';
        END IF;
        IF OLD.status = 'AUTHORITATIVE'
           AND NEW.status = 'AUTHORITATIVE'
           AND OLD.effective_to IS NULL
           AND NEW.effective_to IS NOT NULL
           AND NEW.provider = OLD.provider
           AND NEW.version_code = OLD.version_code
           AND NEW.effective_from = OLD.effective_from
           AND NEW.source_organization = OLD.source_organization
           AND NEW.source_document = OLD.source_document
           AND NEW.source_url IS NOT DISTINCT FROM OLD.source_url
           AND NEW.approval_reference = OLD.approval_reference
           AND NEW.source_checksum IS NOT DISTINCT FROM OLD.source_checksum
           AND NEW.currency = OLD.currency
           AND NEW.includes_tax = OLD.includes_tax
           AND NEW.created_at = OLD.created_at THEN
            RETURN NEW;
        END IF;
        IF OLD.status = 'AUTHORITATIVE' AND NEW.status = 'RETIRED'
           AND NEW.provider = OLD.provider
           AND NEW.version_code = OLD.version_code
           AND NEW.effective_from = OLD.effective_from
           AND NEW.effective_to IS NOT DISTINCT FROM OLD.effective_to
           AND NEW.source_organization = OLD.source_organization
           AND NEW.source_document = OLD.source_document
           AND NEW.source_url IS NOT DISTINCT FROM OLD.source_url
           AND NEW.approval_reference = OLD.approval_reference
           AND NEW.source_checksum IS NOT DISTINCT FROM OLD.source_checksum
           AND NEW.currency = OLD.currency
           AND NEW.includes_tax = OLD.includes_tax
           AND NEW.created_at = OLD.created_at THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'authoritative electricity rate sets are immutable';
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS electricity_rate_sets_immutable ON electricity_rate_sets;
CREATE TRIGGER electricity_rate_sets_immutable
BEFORE UPDATE OR DELETE ON electricity_rate_sets
FOR EACH ROW EXECUTE FUNCTION billing_rate_set_immutable();

CREATE OR REPLACE FUNCTION billing_rate_children_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    set_status VARCHAR(20);
BEGIN
    IF TG_OP <> 'INSERT' THEN
        IF TG_TABLE_NAME = 'electricity_rate_plans' THEN
            SELECT status INTO set_status FROM electricity_rate_sets WHERE id = OLD.rate_set_id;
        ELSE
            SELECT rs.status INTO set_status
            FROM electricity_rate_plans rp
            JOIN electricity_rate_sets rs ON rs.id = rp.rate_set_id
            WHERE rp.id = OLD.rate_plan_id;
        END IF;
        IF set_status IN ('AUTHORITATIVE', 'RETIRED') THEN
            RAISE EXCEPTION 'authoritative electricity rate data is immutable';
        END IF;
    END IF;
    IF TG_OP <> 'DELETE' THEN
        IF TG_TABLE_NAME = 'electricity_rate_plans' THEN
            SELECT status INTO set_status FROM electricity_rate_sets WHERE id = NEW.rate_set_id;
        ELSE
            SELECT rs.status INTO set_status
            FROM electricity_rate_plans rp
            JOIN electricity_rate_sets rs ON rs.id = rp.rate_set_id
            WHERE rp.id = NEW.rate_plan_id;
        END IF;
        IF set_status IN ('AUTHORITATIVE', 'RETIRED') THEN
            RAISE EXCEPTION 'authoritative electricity rate data is immutable';
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS electricity_rate_plans_immutable ON electricity_rate_plans;
CREATE TRIGGER electricity_rate_plans_immutable
BEFORE INSERT OR UPDATE OR DELETE ON electricity_rate_plans
FOR EACH ROW EXECUTE FUNCTION billing_rate_children_immutable();

DROP TRIGGER IF EXISTS electricity_rate_plans_insert_guard ON electricity_rate_plans;
DROP TRIGGER IF EXISTS electricity_rate_tiers_immutable ON electricity_rate_tiers;
CREATE TRIGGER electricity_rate_tiers_immutable
BEFORE INSERT OR UPDATE OR DELETE ON electricity_rate_tiers
FOR EACH ROW EXECUTE FUNCTION billing_rate_children_immutable();

DROP TRIGGER IF EXISTS electricity_rate_tiers_insert_guard ON electricity_rate_tiers;

INSERT INTO electricity_rate_sets
    (provider, version_code, effective_from, effective_to, source_organization, source_document,
     source_url, approval_reference, source_checksum, currency, includes_tax, status)
VALUES
    ('TAIPOWER', 'TAIPOWER_2025_10_01', DATE '2025-10-01', NULL,
     '台灣電力公司 / 經濟部核定', '電價表', NULL,
     '114年9月26日經能字第11458000380號函', NULL, 'TWD', TRUE, 'DRAFT')
ON CONFLICT (provider, version_code) DO NOTHING;

INSERT INTO electricity_tariff_plans
    (plan_code, electricity_tariff, billing_method, usage_class, calculator_kind)
VALUES
    ('LIGHTING_COMMERCIAL_NON_TOU', 'LIGHTING_COMMERCIAL', 'NON_TOU', NULL, 'PROGRESSIVE_NON_TOU'),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL', 'NON_TOU', 'RESIDENTIAL', 'PROGRESSIVE_NON_TOU'),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL', 'NON_TOU', 'NON_RESIDENTIAL_NONCOMMERCIAL', 'PROGRESSIVE_NON_TOU')
ON CONFLICT (plan_code) DO NOTHING;

INSERT INTO electricity_rate_plans (rate_set_id, tariff_plan_id, minimum_monthly_charge)
SELECT sets.id, plans.id, 100.000000
FROM electricity_rate_sets sets
CROSS JOIN electricity_tariff_plans plans
WHERE sets.provider = 'TAIPOWER'
  AND sets.version_code = 'TAIPOWER_2025_10_01'
  AND sets.status = 'DRAFT'
ON CONFLICT (rate_set_id, tariff_plan_id) DO NOTHING;

WITH seed(plan_code, season, tier_order, lower_kwh, upper_kwh, rate_per_kwh) AS (
    VALUES
    ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',1,0::numeric,330::numeric,2.71::numeric),
    ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',2,330,700,3.76),
    ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',3,700,1500,4.46),
    ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',4,1500,3000,7.08),
    ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',5,3000,NULL,7.43),
    ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',1,0,330,2.28),
    ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',2,330,700,3.10),
    ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',3,700,1500,3.61),
    ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',4,1500,3000,5.56),
    ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',5,3000,NULL,5.83),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',1,0,120,1.78),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',2,120,330,2.55),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',3,330,500,3.80),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',4,500,700,5.14),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',5,700,1000,6.44),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',6,1000,NULL,8.86),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',1,0,120,1.78),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',2,120,330,2.26),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',3,330,500,3.13),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',4,500,700,4.24),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',5,700,1000,5.27),
    ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',6,1000,NULL,7.03),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',1,0,120,1.78),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',2,120,330,2.55),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',3,330,500,3.80),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',4,500,700,5.14),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',5,700,1000,6.44),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',6,1000,NULL,8.86),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',1,0,120,1.78),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',2,120,330,2.26),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',3,330,500,3.13),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',4,500,700,4.24),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',5,700,1000,5.27),
    ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',6,1000,NULL,7.03)
)
INSERT INTO electricity_rate_tiers (rate_plan_id, season, tier_order, lower_kwh, upper_kwh, rate_per_kwh)
SELECT rp.id, seed.season, seed.tier_order, seed.lower_kwh, seed.upper_kwh, seed.rate_per_kwh
FROM seed
JOIN electricity_tariff_plans p ON p.plan_code = seed.plan_code
JOIN electricity_rate_plans rp ON rp.tariff_plan_id = p.id
JOIN electricity_rate_sets rs ON rs.id = rp.rate_set_id
WHERE rs.provider = 'TAIPOWER'
  AND rs.version_code = 'TAIPOWER_2025_10_01'
  AND rs.status = 'DRAFT'
ON CONFLICT (rate_plan_id, season, tier_order) DO NOTHING;

UPDATE electricity_rate_sets
SET status = 'AUTHORITATIVE'
WHERE provider = 'TAIPOWER'
  AND version_code = 'TAIPOWER_2025_10_01'
  AND status = 'DRAFT';

DO $$
DECLARE
    target_set_id BIGINT;
    actual_tiers INTEGER;
BEGIN
    SELECT id INTO target_set_id
    FROM electricity_rate_sets
    WHERE provider = 'TAIPOWER' AND version_code = 'TAIPOWER_2025_10_01';
    IF target_set_id IS NULL OR (
        SELECT count(*) FROM electricity_rate_sets
        WHERE provider = 'TAIPOWER' AND version_code = 'TAIPOWER_2025_10_01'
    ) <> 1 THEN
        RAISE EXCEPTION 'TAIPOWER_2025_10_01 rate set seed mismatch';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM electricity_rate_sets
        WHERE id = target_set_id
          AND effective_from = DATE '2025-10-01'
          AND (effective_to IS NULL OR effective_to > effective_from)
          AND source_organization = '台灣電力公司 / 經濟部核定'
          AND source_document = '電價表'
          AND approval_reference = '114年9月26日經能字第11458000380號函'
          AND currency = 'TWD'
          AND includes_tax = TRUE
          AND status IN ('AUTHORITATIVE', 'RETIRED')
    ) THEN
        RAISE EXCEPTION 'TAIPOWER_2025_10_01 rate set metadata mismatch';
    END IF;
    IF (SELECT count(*) FROM electricity_tariff_plans
        WHERE plan_code IN ('LIGHTING_COMMERCIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU')) <> 3 OR EXISTS (
        SELECT 1 FROM electricity_tariff_plans p
        WHERE p.plan_code IN ('LIGHTING_COMMERCIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU')
          AND NOT EXISTS (
            SELECT 1
            FROM (VALUES
                ('LIGHTING_COMMERCIAL_NON_TOU'::varchar, 'LIGHTING_COMMERCIAL'::varchar, 'NON_TOU'::varchar, NULL::varchar, 'PROGRESSIVE_NON_TOU'::varchar),
                ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL', 'NON_TOU', 'RESIDENTIAL', 'PROGRESSIVE_NON_TOU'),
                ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL', 'NON_TOU', 'NON_RESIDENTIAL_NONCOMMERCIAL', 'PROGRESSIVE_NON_TOU')
            ) AS expected(plan_code, electricity_tariff, billing_method, usage_class, calculator_kind)
            WHERE p.plan_code = expected.plan_code
              AND p.electricity_tariff = expected.electricity_tariff
              AND p.billing_method = expected.billing_method
              AND p.usage_class IS NOT DISTINCT FROM expected.usage_class
              AND p.calculator_kind = expected.calculator_kind
        )
    ) OR EXISTS (
        SELECT 1
        FROM (VALUES
            ('LIGHTING_COMMERCIAL_NON_TOU'::varchar, 'LIGHTING_COMMERCIAL'::varchar, 'NON_TOU'::varchar, NULL::varchar, 'PROGRESSIVE_NON_TOU'::varchar),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL', 'NON_TOU', 'RESIDENTIAL', 'PROGRESSIVE_NON_TOU'),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU', 'LIGHTING_NONCOMMERCIAL', 'NON_TOU', 'NON_RESIDENTIAL_NONCOMMERCIAL', 'PROGRESSIVE_NON_TOU')
        ) AS expected(plan_code, electricity_tariff, billing_method, usage_class, calculator_kind)
        WHERE NOT EXISTS (
            SELECT 1 FROM electricity_tariff_plans p
            WHERE p.plan_code = expected.plan_code
              AND p.electricity_tariff = expected.electricity_tariff
              AND p.billing_method = expected.billing_method
              AND p.usage_class IS NOT DISTINCT FROM expected.usage_class
              AND p.calculator_kind = expected.calculator_kind
        )
    ) THEN
        RAISE EXCEPTION 'Billing V1 tariff plan seed mismatch';
    END IF;
    IF (SELECT count(*) FROM electricity_rate_plans WHERE rate_set_id = target_set_id) <> 3 OR EXISTS (
        SELECT 1 FROM electricity_rate_plans rp
        WHERE rp.rate_set_id = target_set_id AND rp.minimum_monthly_charge <> 100.000000
    ) THEN
        RAISE EXCEPTION 'TAIPOWER_2025_10_01 rate plan seed mismatch';
    END IF;

    SELECT count(*) INTO actual_tiers
    FROM electricity_rate_tiers t
    JOIN electricity_rate_plans rp ON rp.id = t.rate_plan_id
    WHERE rp.rate_set_id = target_set_id;
    IF actual_tiers <> 34 THEN
        RAISE EXCEPTION 'TAIPOWER_2025_10_01 tier seed mismatch: got %, want 34', actual_tiers;
    END IF;
    IF EXISTS (
        WITH expected(plan_code, season, tier_order, lower_kwh, upper_kwh, rate_per_kwh) AS (
            VALUES
            ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',1,0::numeric,330::numeric,2.71::numeric),
            ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',2,330,700,3.76),
            ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',3,700,1500,4.46),
            ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',4,1500,3000,7.08),
            ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',5,3000,NULL,7.43),
            ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',1,0,330,2.28),
            ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',2,330,700,3.10),
            ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',3,700,1500,3.61),
            ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',4,1500,3000,5.56),
            ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',5,3000,NULL,5.83),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',1,0,120,1.78),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',2,120,330,2.55),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',3,330,500,3.80),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',4,500,700,5.14),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',5,700,1000,6.44),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',6,1000,NULL,8.86),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',1,0,120,1.78),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',2,120,330,2.26),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',3,330,500,3.13),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',4,500,700,4.24),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',5,700,1000,5.27),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',6,1000,NULL,7.03),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',1,0,120,1.78),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',2,120,330,2.55),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',3,330,500,3.80),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',4,500,700,5.14),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',5,700,1000,6.44),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',6,1000,NULL,8.86),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',1,0,120,1.78),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',2,120,330,2.26),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',3,330,500,3.13),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',4,500,700,4.24),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',5,700,1000,5.27),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',6,1000,NULL,7.03)
        ), actual AS (
            SELECT p.plan_code, t.season, t.tier_order, t.lower_kwh, t.upper_kwh, t.rate_per_kwh
            FROM electricity_rate_tiers t
            JOIN electricity_rate_plans rp ON rp.id = t.rate_plan_id
            JOIN electricity_tariff_plans p ON p.id = rp.tariff_plan_id
            WHERE rp.rate_set_id = target_set_id
        )
        SELECT 1 FROM expected e
        LEFT JOIN actual a ON a.plan_code = e.plan_code AND a.season = e.season AND a.tier_order = e.tier_order
        WHERE a.plan_code IS NULL OR a.lower_kwh IS DISTINCT FROM e.lower_kwh
           OR a.upper_kwh IS DISTINCT FROM e.upper_kwh OR a.rate_per_kwh IS DISTINCT FROM e.rate_per_kwh
    ) OR EXISTS (
        WITH expected(plan_code, season, tier_order) AS (
            VALUES
            ('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',1),('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',2),('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',3),('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',4),('LIGHTING_COMMERCIAL_NON_TOU','SUMMER',5),
            ('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',1),('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',2),('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',3),('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',4),('LIGHTING_COMMERCIAL_NON_TOU','NON_SUMMER',5),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',1),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',2),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',3),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',4),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',5),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','SUMMER',6),
            ('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',1),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',2),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',3),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',4),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',5),('LIGHTING_NONCOMMERCIAL_RESIDENTIAL_NON_TOU','NON_SUMMER',6),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',1),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',2),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',3),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',4),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',5),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','SUMMER',6),
            ('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',1),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',2),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',3),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',4),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',5),('LIGHTING_NONCOMMERCIAL_NONRESIDENTIAL_NON_TOU','NON_SUMMER',6)
        )
        SELECT 1 FROM electricity_rate_tiers t
        JOIN electricity_rate_plans rp ON rp.id = t.rate_plan_id
        JOIN electricity_tariff_plans p ON p.id = rp.tariff_plan_id
        LEFT JOIN expected e ON e.plan_code = p.plan_code AND e.season = t.season AND e.tier_order = t.tier_order
        WHERE rp.rate_set_id = target_set_id AND e.plan_code IS NULL
    ) THEN
        RAISE EXCEPTION 'TAIPOWER_2025_10_01 exact tier seed mismatch';
    END IF;
END;
$$;
