CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS system_configs (
    key VARCHAR(50) PRIMARY KEY,
    value VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Shop remains the existing business entity and is the compatibility
-- implementation of the architecture's Site role in this migration.
CREATE TABLE IF NOT EXISTS shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    address TEXT,
    phone TEXT,
    is_head BOOLEAN NOT NULL DEFAULT false,
    memo TEXT,
    invite_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account VARCHAR(50) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    is_admin BOOLEAN NOT NULL DEFAULT false,
    current_shop_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_shop_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    shop_role VARCHAR(20) NOT NULL DEFAULT 'staff',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT user_shop_relations_user_shop_key UNIQUE (user_id, shop_id)
);

CREATE TABLE IF NOT EXISTS device_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    code VARCHAR(50),
    icon_key VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL DEFAULT 0,
    type_id BIGINT NOT NULL DEFAULT 0,
    mac_address VARCHAR(17) NOT NULL,
    serial_number VARCHAR(128),
    name VARCHAR(100) NOT NULL,
    location VARCHAR(100),
    memo TEXT,
    is_online BOOLEAN NOT NULL DEFAULT false,
    last_seen TIMESTAMPTZ,
    boot_id VARCHAR(80),
    firmware_version VARCHAR(80),
    ip_address VARCHAR(45),
    rssi INTEGER,
    queue_count INTEGER,
    safe_mode BOOLEAN NOT NULL DEFAULT false,
    time_synced BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS device_alert_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL UNIQUE,
    daily_limit_kwh DOUBLE PRECISION,
    monthly_limit_kwh DOUBLE PRECISION,
    non_usage_start_time VARCHAR(255),
    non_usage_end_time VARCHAR(255),
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS measurement_points (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id BIGINT NOT NULL REFERENCES shops(id),
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS device_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id BIGINT NOT NULL REFERENCES devices(id),
    measurement_point_id UUID NOT NULL REFERENCES measurement_points(id),
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT device_assignments_valid_range_check
        CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE TABLE IF NOT EXISTS telemetry_ingest_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id BIGINT NOT NULL REFERENCES devices(id),
    boot_counter BIGINT NOT NULL,
    sequence BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    received_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- This starts as an ordinary table. Migration 000002 applies the
-- TimescaleDB-specific primary key and hypertable conversion.
CREATE TABLE IF NOT EXISTS power_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    measurement_point_id UUID REFERENCES measurement_points(id),
    device_id BIGINT NOT NULL REFERENCES devices(id),
    voltage NUMERIC(5,2),
    current NUMERIC(5,2),
    power NUMERIC(8,2),
    active_power NUMERIC(8,2),
    kwh_total NUMERIC(10,3),
    energy_delta_kwh NUMERIC(10,6),
    power_factor NUMERIC(5,4),
    rssi INTEGER,
    protocol_version INTEGER NOT NULL DEFAULT 0,
    boot_id VARCHAR(80),
    boot_counter BIGINT,
    sequence BIGINT,
    valid_samples INTEGER,
    invalid_samples INTEGER,
    firmware_version VARCHAR(80),
    fw VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS alert_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES devices(id),
    type VARCHAR(50),
    message TEXT,
    voltage NUMERIC(5,2),
    current NUMERIC(5,2),
    power NUMERIC(8,2),
    is_read BOOLEAN NOT NULL DEFAULT false,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS daily_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date VARCHAR(10) NOT NULL,
    device_id BIGINT NOT NULL REFERENCES devices(id),
    kwh_usage NUMERIC(10,3),
    carbon_kg NUMERIC(10,3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_devices_shop_id ON devices (shop_id);
CREATE INDEX IF NOT EXISTS idx_devices_type_id ON devices (type_id);
CREATE INDEX IF NOT EXISTS idx_alert_logs_device_id ON alert_logs (device_id);
CREATE INDEX IF NOT EXISTS idx_alert_logs_created_at ON alert_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_daily_usages_date ON daily_usages (date);
CREATE INDEX IF NOT EXISTS idx_daily_usages_device_id ON daily_usages (device_id);
