-- Dashboard Carbon Summary. This reversible feature migration is separate
-- from protected B-02 coverage migration 000007.
ALTER TABLE shops
    ADD COLUMN IF NOT EXISTS electricity_tariff VARCHAR(32);
ALTER TABLE shops
    DROP CONSTRAINT IF EXISTS shops_electricity_tariff_check;
ALTER TABLE shops
    ADD CONSTRAINT shops_electricity_tariff_check CHECK (
        electricity_tariff IS NULL OR electricity_tariff IN (
            'LIGHTING_COMMERCIAL', 'LOW_VOLTAGE', 'HIGH_VOLTAGE',
            'EXTRA_HIGH_VOLTAGE', 'LIGHTING_NONCOMMERCIAL', 'PACKAGE_LIGHTING'
        )
    );

CREATE TABLE IF NOT EXISTS carbon_factor_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization VARCHAR(200) NOT NULL,
    document_title VARCHAR(200) NOT NULL,
    source_url VARCHAR(500) NOT NULL,
    version_year INTEGER NOT NULL,
    roc_year INTEGER NOT NULL,
    unit VARCHAR(32) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT carbon_factor_sets_version_key UNIQUE (version_year, roc_year),
    CONSTRAINT carbon_factor_sets_unit_check CHECK (unit = 'kgCO2e/kWh')
);

CREATE UNIQUE INDEX IF NOT EXISTS carbon_factor_sets_one_active
    ON carbon_factor_sets (is_active) WHERE is_active;

CREATE TABLE IF NOT EXISTS carbon_factor_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL REFERENCES carbon_factor_sets(id) ON DELETE CASCADE,
    tariff_code VARCHAR(32) NOT NULL,
    factor_kgco2e_per_kwh NUMERIC(10,6) NOT NULL,
    CONSTRAINT carbon_factor_rates_set_tariff_key UNIQUE (set_id, tariff_code),
    CONSTRAINT carbon_factor_rates_tariff_check CHECK (tariff_code IN (
        'LIGHTING_COMMERCIAL', 'LOW_VOLTAGE', 'HIGH_VOLTAGE',
        'EXTRA_HIGH_VOLTAGE', 'LIGHTING_NONCOMMERCIAL', 'PACKAGE_LIGHTING'
    )),
    CONSTRAINT carbon_factor_rates_nonnegative_check CHECK (factor_kgco2e_per_kwh >= 0)
);

INSERT INTO carbon_factor_sets
    (organization, document_title, source_url, version_year, roc_year, unit, is_active)
VALUES
    ('經濟部能源署', '114年度電力排碳係數',
     'https://www.moeaea.gov.tw/ecw/populace/content/ContentDesc.aspx?menu_id=27028',
     2025, 114, 'kgCO2e/kWh', true)
ON CONFLICT (version_year, roc_year) DO UPDATE SET
    organization = EXCLUDED.organization,
    document_title = EXCLUDED.document_title,
    source_url = EXCLUDED.source_url,
    unit = EXCLUDED.unit,
    is_active = EXCLUDED.is_active;

INSERT INTO carbon_factor_rates (set_id, tariff_code, factor_kgco2e_per_kwh)
SELECT sets.id, rates.tariff_code, rates.factor_kgco2e_per_kwh
FROM carbon_factor_sets AS sets
CROSS JOIN (VALUES
    ('LIGHTING_COMMERCIAL', 0.466::numeric),
    ('LOW_VOLTAGE', 0.466::numeric),
    ('HIGH_VOLTAGE', 0.466::numeric),
    ('EXTRA_HIGH_VOLTAGE', 0.466::numeric),
    ('LIGHTING_NONCOMMERCIAL', 0.471::numeric),
    ('PACKAGE_LIGHTING', 0.471::numeric)
) AS rates(tariff_code, factor_kgco2e_per_kwh)
WHERE sets.version_year = 2025 AND sets.roc_year = 114
ON CONFLICT (set_id, tariff_code) DO UPDATE SET
    factor_kgco2e_per_kwh = EXCLUDED.factor_kgco2e_per_kwh;
