DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM devices LIMIT 1)
       OR EXISTS (SELECT 1 FROM device_assignments LIMIT 1)
       OR EXISTS (SELECT 1 FROM measurement_points LIMIT 1)
       OR EXISTS (SELECT 1 FROM telemetry_ingest_keys LIMIT 1)
       OR EXISTS (SELECT 1 FROM power_readings LIMIT 1) THEN
        RAISE EXCEPTION USING
            ERRCODE = 'P0001',
            MESSAGE = 'MIGRATION_GUARDED_DOWN',
            DETAIL = 'refusing rollback of Timescale identity migration while affected data exists; restore a backup or use a forward compatibility migration';
    END IF;
END
$$;

ALTER TABLE device_assignments
    DROP CONSTRAINT IF EXISTS device_assignments_device_no_overlap;
ALTER TABLE device_assignments
    DROP CONSTRAINT IF EXISTS device_assignments_measurement_point_no_overlap;
DROP INDEX IF EXISTS idx_device_assignments_device_history;
DROP INDEX IF EXISTS idx_device_assignments_measurement_point_history;
DROP INDEX IF EXISTS telemetry_ingest_keys_identity_key;
DROP INDEX IF EXISTS devices_serial_number_key;
DROP INDEX IF EXISTS devices_mac_address_canonical_key;
ALTER TABLE devices DROP CONSTRAINT IF EXISTS devices_mac_canonical_check;

DROP TABLE power_readings;
CREATE TABLE power_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    measurement_point_id UUID REFERENCES measurement_points(id),
    device_id BIGINT NOT NULL REFERENCES devices(id),
    voltage NUMERIC(5,2),
    current NUMERIC(5,2),
    power NUMERIC(8,2),
    active_power NUMERIC(8,2),
    kwh_total NUMERIC(10,3),
    energy_delta_kwh NUMERIC(10,6),
    power_factor NUMERIC(5,4),
    rssi INTEGER,
    protocol_version INTEGER NOT NULL DEFAULT 0,
    boot_id VARCHAR(80),
    boot_counter BIGINT,
    sequence BIGINT,
    valid_samples INTEGER,
    invalid_samples INTEGER,
    firmware_version VARCHAR(80),
    fw VARCHAR(80)
);
